spring:
  main:
    banner-mode: off
  h2:
    console:
      path: /problemStore_h2
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:problemStore_db
    username: sa
    password: password
