spring:
  profiles:
    active: unsecure
  main:
    banner-mode: off
  h2:
    console:
      path: /problemStore_h2
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:problemStore_db
    username: sa
    password: password
  sql:
    init:
      schema-locations: classpath:db/ddl-scripts.sql
      data-locations: classpath:db/dml-scripts.sql
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      tracking-modes: cookie
logging:
  level:
    com:
      Babaitis:
        Project:
          ProblemStore:
            config: DEBUG
            problem: INFO
            filter: TRACE
