spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ekspla
    username: user
    password: password
  sql:
    init:
      schema-locations: classpath:db/mysql/ddl-scripts-my.sql
      data-locations: classpath:db/dml-scripts.sql
      platform: mysql
      mode: always